# Data Types
INTEGER = "INTEGER"
INTEGER32 = "INTEGER32"
UINTEGER32 = "UINTEGER32"
OCTETSTRING = "OCTETSTRING"
OID = "OID"
IPADDRESS = "IPADDRESS"

DataTypes = [INTEGER,INTEGER32,UINTEGER32,OCTETSTRING,OID,IPADDRESS]
NUMERIC = [INTEGER,INTEGER32,UINTEGER32]
STRING = [OCTETSTRING,OID,IPADDRESS]

#Comm Setting
STATIC = "static"
DYNAMIC = "dynamic"
